travis:
  secure:
    BINSTAR_TOKEN: fqGOlBU4vRAGKBMLRAkatrJrww3qmCUbmxqEq/XAEd7/oqN7P2Ur3TMlyG742rX2eXzgm0X6kToloNnNQ5aISUZJyFum84bcczKQibW3WPrMscK4r8tWOGB4AV31dkkAzUSNIPjPb/upSyvaZbkfCprgxR2Ok61KQBicxs01xUjEmpL1RODf9mVpLhfqGcA94gExUlkBqPrNey+3ZvEAKbABXVOFnhrNbcStvsjd0Zsh2p7fafW2ImzCVEe9hy5U3jy13zf7UGWnIv2m7ahkHY6WNLeY3uTGmFWaSafRRFdHHgX5T5J7zEn/+p4nE9HaT4yGtnV9aTCTV2CORSPr4c1uC3z7Gx/DDmJn3tl0G/RM7i2ibUktbWdskK57Cul9e/rVdjYWfGbwiLHlGqmo+IEI9JncN/H6ZH4pSeYSaUVvRHP6BEF25gln70wJIKIM0IWkJIg3mAwdN/GVzZvyWMr7jBIPN8/bTW8ilTwbK4qpmkMC1wQ/afW4fyLJcMHHZoxpUrtWcsc6kLBU6xPUGWBCpte96gL+NzrFddmTjCIphKijCn1PcxGUvlxjig3n+Y3ZmRZYIlyy+qxs4duNoQAsMwZDStxQW7KzM9iIddBjyqgLA2Aq5K5oKwVnW3SztOTXhIr37aamXkMJX/jDA+5Eb4hhtTEG3RyFKBoXABw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
