appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: 4mhje6Zq03Wfhz6zokAQL9qPBt0tQ3Ru/I8XNdqxS3WxujbNwdjOvkvqSuT1w1J+4P9He1c46i2nCWity3xKKV/2a8TiUzEL31/+yct/HucLS8U3DHtJVZOFAp7BjAM0WrPnD+nx6kEP22Kd4QwbCfU2fvWFqZBCnoyMe59vEpC9XL+VqJmERWDYzS1LJfIDsh+AjNTGTo327oOqUmhrWRy1y4D4YGkeInbb4Xw6zF3sluF2aFh+w+odgEPa8OY+l0gl5mCYpN3KOeJqDrvzYVOjFWXIM8cpQ2nBfHheSTIKYyA7wEwvOZUheqgvaRuaMPZM+vp/MUaDVKFXuDcR1E5qAJKa2CpbphWw2l91RQDSJ5srsgt1TtZZAuvSSTMRRLXW5rSVuipwDtEx1a9sRkRjKVf1/ledzZeR0vtSPTLymzRRhxXHmPbZjuIJ9mHqLwCrX32mxiWcgGioUbKgYFQZkVSzN7ryWWFtPBEJBBIz70zEG17rvtcDMUukDPTd7lK53SQSfbD/aZ+MbbQ0OBMMaz6oRQ3hCsEu0kKcLoHvoLROkjaiWVK8lerIQG60DXdsDTOIj9A4kCW/kDtZ9U7SF7TTLZXxYFXI3wiHedYmKq2llmjXjlKZMVhmYcwwEPRFVhInNrAJaios2Cy40Ujbl1rXEbVhUhKhLHFf/2Y=
conda_forge_output_validation: false
